# Generated by Django 5.2 on 2025-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=255)),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                ("editorial", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "encuadernacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ebook", "Ebook"),
                            ("blanda", "Tapa blanda"),
                            ("dura", "Tapa dura"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "calificacion",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("reseña", models.TextField(blank=True, null=True)),
                ("citas", models.TextField(blank=True, null=True)),
                ("paginas", models.IntegerField(blank=True, null=True)),
                ("año_publicacion", models.IntegerField(blank=True, null=True)),
                ("genero", models.CharField(blank=True, max_length=100, null=True)),
                ("es_relectura", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("leido", "Leído"),
                            ("quiero_leer", "Quiero leer"),
                            ("abandonado", "Abandonado"),
                        ],
                        default="leido",
                        max_length=20,
                    ),
                ),
                ("etiquetas", models.ManyToManyField(blank=True, to="libros.etiqueta")),
            ],
        ),
    ]
