# Generated by Django 5.2 on 2025-04-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="encuadernacion",
        ),
        migrations.AddField(
            model_name="libro",
            name="formato",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ebook", "Ebook"),
                    ("blanda", "Tapa blanda"),
                    ("dura", "Tapa dura"),
                    ("audiolibro", "Audiolibro"),
                ],
                default="ebook",
                max_length=50,
                null=True,
            ),
        ),
    ]
