# Generated by Django 5.2 on 2025-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0002_remove_libro_encuadernacion_libro_formato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="calificacion",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "⭐"),
                    (2, "⭐⭐"),
                    (3, "⭐⭐⭐"),
                    (4, "⭐⭐⭐⭐"),
                    (5, "⭐⭐⭐⭐⭐"),
                ],
                null=True,
            ),
        ),
    ]
