# Generated by Django 5.2 on 2025-04-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0003_alter_libro_calificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="portada",
            field=models.ImageField(blank=True, null=True, upload_to="portadas/"),
        ),
    ]
