# Generated by Django 5.2 on 2025-04-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0004_libro_portada"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libro",
            old_name="reseña",
            new_name="notas",
        ),
    ]
