# Generated by Django 5.2 on 2025-04-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0005_rename_reseña_libro_notas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="editorial",
        ),
    ]
