# Generated by Django 5.2 on 2025-04-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0006_remove_libro_editorial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="es_relectura",
        ),
    ]
